#数据库配置(MySQL)
Database:
  Type: "MySQL"
  Driver: "pymysql"
  Host: "localhost"
  Port: 3306
  Database: "moyun"
  Account: "MoYun_Admin"
  Password: "MoYun_Admin"

# 平台管理员账号
Admin:
  Account: "MoYun_Admin"
  Password: "MoYun_Admin"
  ID: 1 
  # 以下是profile页的一些外显的个人信息，不写的留空即可
  E-Mail: ""
  Telephone: ""
  Signature: "道阻且长" # 管理员签名(可以理解为类似于QQ签名的东西)
  ProfilePhoto: "" # 请在此指定管理员头像的路径

# 邮箱服务配置
E-Mail:
  Host: "smtp.126.com" # smtp邮箱服务器，如“smtp.126.com”
  Port: 465 # smtp端口，常用的有25和465
  Username: "" # 用于在邮箱服务器上登录的账号，通常默认为完整的邮箱“admin@126.com”
  Password: "" # 发件人SMTP密钥(通常不是邮箱密码，而是邮箱服务商提供的一串密钥)
  Sender: "" # 完整邮箱，如“admin@126.com”

# Flask配置
Flask:
  SECRET_KEY: "MoYun" # Flask混淆密钥，用于session加密
  JSON_AS_ASCII: False # Flask返回json时是否使用ascii编码，False才可保证中文不乱码
  PERMANENT_SESSION_LIFETIME: 86400 # session有效期，单位秒，默认1天
  Port: 5000 # Flask运行端口，默认5000

# Redis配置(在Windows下使用memurai替代)
Redis:
  host: "localhost" # Redis地址
  port: 6379 # Redis端口
  database: 0 # Redis数据库
  password: "" # Redis密码

# API配置
Yiketianqi: # 一刻天气API
  version: "v61"
  appid: ""
  appsecret: ""

Qwen: # 阿里 通义千问API
  api_key: "" # API_KEY
  model: "qwen-max" # 调用的模型